### ISSUE TITLE
[Question/Suggestion] Zou client and help

### ISSUE THREAD

**Issue by k0pernicus** [pop-os/parallel-getter#1]
This is a nice project :)  
I worked on the same thing as a replacement for "wget" called "zou": https://github.com/k0pernicus/zou.  
If you want any help on the project, please to ping me - I would be glad to fill/solve any issues, or add some features... 
 
Good luck!

**Comment by mmstick** [comment]
@k0pernicus Feel free to submit a PR if you're interested in contributing. This has been developed for our [debrep](https://github.com/pop-os/debrepbuild) repository tool.
